import { useState } from "react";
import { AlertTriangle, ClipboardCheck, HeartPulse, Home, ShieldAlert, type LucideIcon } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Status = "PRESENT" | "ABSENT" | "LATE" | "EXCUSED";
const inputClass = "mt-1.5";

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-slate-700">{label}{children}</label>; }
function SectionIntro({ icon: Icon, eyebrow, title, description }: { icon: typeof ClipboardCheck; eyebrow: string; title: string; description: string }) { return <div className="mb-5 flex items-start gap-3"><div className="mt-0.5 flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/80">{eyebrow}</p><h2 className="mt-1 text-lg font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div></div>; }

export default function Welfare() {
  const { data, refetch } = trpc.welfare.dashboard.useQuery();
  const recordAttendance = trpc.welfare.recordAttendance.useMutation({ onSuccess: result => { toast.success(`${result.records} attendance records saved; ${result.guardianAlertsQueued} guardian alerts queued`); refetch(); }, onError: error => toast.error(error.message) });
  const createIncident = trpc.welfare.createDisciplineIncident.useMutation({ onSuccess: () => { toast.success("Discipline incident recorded"); refetch(); }, onError: error => toast.error(error.message) });
  const addAction = trpc.welfare.addDisciplineAction.useMutation({ onSuccess: () => toast.success("Discipline action recorded"), onError: error => toast.error(error.message) });
  const createWelfare = trpc.welfare.createWelfareCase.useMutation({ onSuccess: () => toast.success("Welfare case created"), onError: error => toast.error(error.message) });
  const createReferral = trpc.welfare.createSafeguardingReferral.useMutation({ onSuccess: () => toast.success("Safeguarding referral submitted"), onError: error => toast.error(error.message) });
  const upsertMedical = trpc.welfare.upsertMedicalProfile.useMutation({ onSuccess: () => toast.success("Medical profile saved"), onError: error => toast.error(error.message) });
  const createExeat = trpc.welfare.createExeatRequest.useMutation({ onSuccess: () => toast.success("Exeat request created"), onError: error => toast.error(error.message) });
  const [learnerId, setLearnerId] = useState("");
  const [attendanceStatus, setAttendanceStatus] = useState<Status>("PRESENT");
  const [mode, setMode] = useState<"DAILY" | "PERIOD" | "BOARDING_ROLL_CALL">("DAILY");
  const [incident, setIncident] = useState({ category: "", summary: "", severity: "1" });
  const [action, setAction] = useState({ incidentId: "", actionType: "DEMERIT", points: "" });
  const [welfare, setWelfare] = useState({ category: "", summary: "", severity: "1", privateNotes: "" });
  const [referral, setReferral] = useState({ welfareCaseId: "", referralType: "", details: "", externalAgency: "" });
  const [medical, setMedical] = useState({ bloodGroup: "", allergies: "", conditions: "", medications: "", emergencyContactName: "", emergencyContactPhone: "" });
  const [exeat, setExeat] = useState({ departureAt: "", expectedReturnAt: "", destination: "", reason: "" });
  const learners = data?.attendance ?? [];
  const metrics: Array<[string, number, LucideIcon]> = [["Absences", data?.counts.absences ?? 0, AlertTriangle], ["Late arrivals", data?.counts.lateArrivals ?? 0, ClipboardCheck], ["Discipline", data?.disciplineCount ?? 0, ShieldAlert], ["Welfare", data?.welfareCount ?? 0, HeartPulse], ["Safeguarding", data?.safeguardingCount ?? 0, ShieldAlert], ["Exeat requests", data?.exeatCount ?? 0, Home]];
  const createAttendance = () => { if (!learnerId) return toast.error("Enter a learner ID"); recordAttendance.mutate({ academicYearId: 1, termId: 1, sessionDate: new Date(), mode, periodNumber: mode === "PERIOD" ? 1 : null, periodName: mode === "PERIOD" ? "Period 1" : null, records: [{ learnerId: Number(learnerId), status: attendanceStatus, reason: attendanceStatus === "EXCUSED" ? "Approved absence" : null }] }); };
  return <div className="min-h-screen bg-[#f6f8fb] text-slate-900"><div className="border-b border-slate-200/70 bg-[#0f3049] px-5 py-8 text-white sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-6"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-[#e4c477]"><HeartPulse className="h-4 w-4" /> Stage 5 · attendance & learner welfare</div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Care records with privacy by design.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-blue-100/80">Record attendance, respond to discipline, support learners, and manage boarding movements without exposing sensitive case details to general users.</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-xs text-blue-100/70">Sensitive data</p><p className="mt-1 text-lg font-semibold">Role restricted</p></div></div></div></div>
  <main className="mx-auto max-w-7xl space-y-7 px-5 py-8 sm:px-8 lg:px-10"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{metrics.map(([label, value, Icon]) => <Card key={String(label)}><CardContent className="p-4"><Icon className="h-4 w-4 text-primary" /><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value as number}</p></CardContent></Card>)}</div>
  <Tabs defaultValue="attendance" className="space-y-7"><TabsList className="h-auto w-full justify-start gap-1 overflow-x-auto rounded-2xl border border-slate-200 bg-white p-1.5"><TabsTrigger value="attendance">Attendance</TabsTrigger><TabsTrigger value="discipline">Discipline</TabsTrigger><TabsTrigger value="welfare">Welfare & safeguarding</TabsTrigger><TabsTrigger value="boarding">Boarding & medical</TabsTrigger></TabsList>
  <TabsContent value="attendance" className="space-y-7"><SectionIntro icon={ClipboardCheck} eyebrow="Daily · period · boarding" title="Attendance history and guardian alerts" description="Attendance records are immutable. Absences and late arrivals queue an auditable guardian alert." /><Card><CardHeader><CardTitle className="text-base">Record attendance</CardTitle><CardDescription>Use the same capture flow for daily attendance, period attendance, and boarding roll call.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Learner ID"><Input className={inputClass} value={learnerId} onChange={e => setLearnerId(e.target.value)} placeholder="Learner ID" /></Field><Field label="Mode"><select className="mt-1.5 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm" value={mode} onChange={e => setMode(e.target.value as typeof mode)}><option value="DAILY">Daily</option><option value="PERIOD">Period</option><option value="BOARDING_ROLL_CALL">Boarding roll call</option></select></Field><Field label="Status"><select className="mt-1.5 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm" value={attendanceStatus} onChange={e => setAttendanceStatus(e.target.value as Status)}><option value="PRESENT">Present</option><option value="ABSENT">Absent</option><option value="LATE">Late</option><option value="EXCUSED">Excused absence</option></select></Field><div className="flex items-end"><Button className="w-full bg-[#0f3049]" onClick={createAttendance}>Save attendance</Button></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Recent attention indicators</CardTitle><CardDescription>General dashboard view contains status indicators only, not welfare or counselling details.</CardDescription></CardHeader><CardContent className="space-y-2">{learners.slice(0, 8).map(row => <div key={row.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-3"><div><p className="text-sm font-medium">Learner #{row.learnerId}</p><p className="text-xs text-slate-500">Attendance status: {row.status}</p></div><Badge variant={row.status === "PRESENT" ? "secondary" : "destructive"}>{row.status}</Badge></div>)}</CardContent></Card></TabsContent>
  <TabsContent value="discipline" className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Discipline incident</CardTitle><CardDescription>Capture an incident first, then attach demerits, detention, or suspension as a separate action.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="Learner ID"><Input className={inputClass} value={learnerId} onChange={e => setLearnerId(e.target.value)} /></Field><Field label="Category"><Input className={inputClass} value={incident.category} onChange={e => setIncident({ ...incident, category: e.target.value })} placeholder="Attendance, conduct, uniform" /></Field><Field label="Summary"><Input className={inputClass} value={incident.summary} onChange={e => setIncident({ ...incident, summary: e.target.value })} /></Field><Button className="w-full" onClick={() => createIncident.mutate({ learnerId: Number(learnerId), occurredAt: new Date(), category: incident.category, severity: Number(incident.severity), summary: incident.summary })}>Record incident</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Demerit, detention, or suspension</CardTitle><CardDescription>Actions remain linked to the originating incident for auditability.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="Incident ID"><Input className={inputClass} value={action.incidentId} onChange={e => setAction({ ...action, incidentId: e.target.value })} /></Field><Field label="Action"><select className="mt-1.5 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm" value={action.actionType} onChange={e => setAction({ ...action, actionType: e.target.value })}><option value="DEMERIT">Demerit</option><option value="DETENTION">Detention</option><option value="SUSPENSION">Suspension</option></select></Field><Field label="Demerit points"><Input className={inputClass} type="number" value={action.points} onChange={e => setAction({ ...action, points: e.target.value })} /></Field><Button className="w-full" onClick={() => addAction.mutate({ incidentId: Number(action.incidentId), actionType: action.actionType as "DEMERIT" | "DETENTION" | "SUSPENSION", points: action.points ? Number(action.points) : null })}>Save disciplinary action</Button></CardContent></Card></TabsContent>
  <TabsContent value="welfare" className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Authorized welfare case</CardTitle><CardDescription>Case summary and private notes are only returned to users with the welfare-sensitive permission.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="Learner ID"><Input className={inputClass} value={learnerId} onChange={e => setLearnerId(e.target.value)} /></Field><Field label="Category"><Input className={inputClass} value={welfare.category} onChange={e => setWelfare({ ...welfare, category: e.target.value })} placeholder="Wellbeing, family, protection" /></Field><Field label="Case summary"><Input className={inputClass} value={welfare.summary} onChange={e => setWelfare({ ...welfare, summary: e.target.value })} /></Field><Field label="Private notes"><textarea className="mt-1.5 min-h-24 w-full rounded-md border border-slate-200 p-3 text-sm" value={welfare.privateNotes} onChange={e => setWelfare({ ...welfare, privateNotes: e.target.value })} /></Field><Button className="w-full" onClick={() => createWelfare.mutate({ learnerId: Number(learnerId), category: welfare.category, summary: welfare.summary, severity: Number(welfare.severity), privateNotes: welfare.privateNotes || null })}>Create protected case</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Safeguarding referral</CardTitle><CardDescription>Referrals carry a restricted status and never appear in the general attention feed.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="Welfare case ID"><Input className={inputClass} value={referral.welfareCaseId} onChange={e => setReferral({ ...referral, welfareCaseId: e.target.value })} /></Field><Field label="Referral type"><Input className={inputClass} value={referral.referralType} onChange={e => setReferral({ ...referral, referralType: e.target.value })} /></Field><Field label="Details"><textarea className="mt-1.5 min-h-24 w-full rounded-md border border-slate-200 p-3 text-sm" value={referral.details} onChange={e => setReferral({ ...referral, details: e.target.value })} /></Field><Button className="w-full" onClick={() => createReferral.mutate({ welfareCaseId: Number(referral.welfareCaseId), learnerId: Number(learnerId), referralType: referral.referralType, details: referral.details, externalAgency: referral.externalAgency || null })}>Submit referral</Button></CardContent></Card></TabsContent>
  <TabsContent value="boarding" className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Medical and emergency profile</CardTitle><CardDescription>Access is separately permissioned for sensitive health information.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="Learner ID"><Input className={inputClass} value={learnerId} onChange={e => setLearnerId(e.target.value)} /></Field><Field label="Blood group"><Input className={inputClass} value={medical.bloodGroup} onChange={e => setMedical({ ...medical, bloodGroup: e.target.value })} /></Field><Field label="Allergies"><Input className={inputClass} value={medical.allergies} onChange={e => setMedical({ ...medical, allergies: e.target.value })} /></Field><Field label="Emergency contact"><Input className={inputClass} value={medical.emergencyContactName} onChange={e => setMedical({ ...medical, emergencyContactName: e.target.value })} /></Field><Button className="w-full" onClick={() => upsertMedical.mutate({ learnerId: Number(learnerId), ...medical })}>Save protected medical profile</Button></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Boarder exeat request</CardTitle><CardDescription>Requests require a destination, reason, departure, and expected return time.</CardDescription></CardHeader><CardContent className="space-y-4"><Field label="Learner ID"><Input className={inputClass} value={learnerId} onChange={e => setLearnerId(e.target.value)} /></Field><Field label="Departure"><Input className={inputClass} type="datetime-local" value={exeat.departureAt} onChange={e => setExeat({ ...exeat, departureAt: e.target.value })} /></Field><Field label="Expected return"><Input className={inputClass} type="datetime-local" value={exeat.expectedReturnAt} onChange={e => setExeat({ ...exeat, expectedReturnAt: e.target.value })} /></Field><Field label="Destination"><Input className={inputClass} value={exeat.destination} onChange={e => setExeat({ ...exeat, destination: e.target.value })} /></Field><Field label="Reason"><Input className={inputClass} value={exeat.reason} onChange={e => setExeat({ ...exeat, reason: e.target.value })} /></Field><Button className="w-full" onClick={() => createExeat.mutate({ learnerId: Number(learnerId), departureAt: new Date(exeat.departureAt), expectedReturnAt: new Date(exeat.expectedReturnAt), destination: exeat.destination, reason: exeat.reason })}>Submit exeat request</Button></CardContent></Card></TabsContent></Tabs></main></div>;
}
